### PR TITLE
Added some cool stuff like data types, edited package.json and other stuff.

### PR DESCRIPTION
**Pull request by MrBisquit**

### CODE REVIEW

**Review by believemanasseh — CHANGES_REQUESTED** [review]
`type User = {
    firstName: string;
    lastName: string;
    email: string;
    image: string; // Needs to be an actual image.
}`

The User type class should include the username, email and password I guess. The firstname and lastname properties not needed. Please refer to the ERD.

**Comment by MrBisquit** [comment]
> `type User = {
>     firstName: string;
>     lastName: string;
>     email: string;
>     image: string; // Needs to be an actual image.
> }`
> 
> The User type class should include the username, email and password I guess. The firstname and lastname properties not needed. Please refer to the ERD. 
> 
I copied this from backend and I didn't see any username tag, I can do one anyway though if you want.

**Comment by believemanasseh** [comment]
> > `type User = { firstName: string; lastName: string; email: string; image: string; // Needs to be an actual image. }`
> > The User type class should include the username, email and password I guess. The firstname and lastname properties not needed. Please refer to the ERD.
> 
> I copied this from backend and I didn't see any username tag, I can do one anyway though if you want.

The firstName and lastName properties are not needed either. You can take a look at the ERD below

image

**Comment by MrBisquit** [comment]
@believemanasseh I have done this.

> > > `type User = { firstName: string; lastName: string; email: string; image: string; // Needs to be an actual image. }`
> > > The User type class should include the username, email and password I guess. The firstname and lastname properties not needed. Please refer to the ERD.
> > 
> > 
> > I copied this from backend and I didn't see any username tag, I can do one anyway though if you want.
> 
> The firstName and lastName properties are not needed either. You can take a look at the ERD below
> 
> image

**Pull request closed without merging**
