### PR TITLE
Updated README with style guide for react

### PR DESCRIPTION
**Pull request by believemanasseh**
Added Airbnb style guide for React/JSX

### CODE REVIEW

**Review by MrBisquit — CHANGES_REQUESTED** [review]
No README was updated.

**Comment by believemanasseh** [comment]
@MrBisquit fixed that

**Review by Diegogagan2587 — APPROVED** [review]
# Approved :green_circle: :green_circle:  :green_circle:  :green_circle: 

Good Job buddy, looks nice!

**Review by SHIV5T3R — APPROVED** [review]
lgtm

**Pull request merged**
